kind: Service
apiVersion: v1
metadata:
  name: {{ template "btcd.fullname" . }}-lb
  labels:
    app: {{ template "btcd.name" . }}
    chart: {{ template "btcd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "btcd.name" . }}
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 18333
    targetPort: 18333
  clusterIP:
  loadBalancerIP:
  type: LoadBalancer
